-- Create the guestbook table
create table public.guestbook (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  content text not null
);

-- Set up Row Level Security (RLS)
alter table public.guestbook enable row level security;

-- Create a policy that allows anyone to read messages
create policy "Enable read access for all users"
on public.guestbook
for select
using (true);

-- Create a policy that allows anyone to insert messages (anon)
create policy "Enable insert access for all users"
on public.guestbook
for insert
with check (true);
